name: build

on:
  push:
    branches:
      # long-lived branches
      - master

  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}
    container:
      image: trufflesuite/ganache-cli:latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: npm build
      run: npm run build
      env:
        MNENOMIC: ${{secrets.MNENOMIC}}
        INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}

    - name: npm deploy
      run: npm run deploy -- --reset --dry-run
      env:
        MNENOMIC: ${{secrets.MNENOMIC}}
        INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}

    - name: npm config-gen
      run: npm run config-gen
      env:
        MNENOMIC: ${{secrets.MNENOMIC}}
        INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}

    - name: npm test
      run: npm run test
      env:
        MNENOMIC: ${{secrets.MNENOMIC}}
        INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: networks-$GITHUB_REF-$GITHUB_SHA
        path: |
          networks
          build
