name: release

on:
  release:
    types: [created]

jobs:
#  build:
#    strategy:
#      matrix:
#        platform: [ ubuntu-latest ]
#        node-version: [ 12.x ]
#    runs-on: ${{ matrix.platform }}
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: npm build
#        run: npm run build
#        env:
#          MNENOMIC: ${{secrets.MNENOMIC}}
#          INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
#
#      - name: npm ropsten:deploy
#        run: npm run ropsten:deploy
#        env:
#          MNENOMIC: ${{secrets.MNENOMIC}}
#          INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
#
#      - name: npm ropsten:config-gen
#        run: npm run ropsten:config-gen
#        env:
#          MNENOMIC: ${{secrets.MNENOMIC}}
#          INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
#
#      - name: npm test
#        run: npm run test
#        env:
#          MNENOMIC: ${{secrets.MNENOMIC}}
#          INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
#
#      - name: Archive artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: networks
#          path: |
#            networks
#            build

  publish:
#    needs: build
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node-version: [ 12.x ]
      runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

#      - name: Download networks
#        uses: actions/download-artifact@v2
#        with:
#          name: networks

      - name: Publish beta # Публикуем бету
      run: |
        mkdir ~/networks-npm
        cp -r networks/* ~/networks-npm/
        npm version ${{ github.event.release.tag_name }
        npm publish --tag ${{ github.event.release.tag_name }
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
